api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        extra_properties:
            standard_put: true
        route_prefix: "api"

    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default: itemsPerPage

    # Documenting the Authentication Mechanism with Swagger/Open API
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
