lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # user_identity_field => field to place in token payload
    user_identity_field: email # Or the field you have setted using make:user
    token_ttl: 3600 # token TTL in seconds, defaults to 1(3600s) hour, 86400(24h)

    # LexikJWTAuthenticationBundle automatically add an OpenAPI endpoint 
    # to conveniently retrieve the token in Swagger UI.
    # -> modify the default configuration
    api_platform:
        check_path: /auth
        username_path: email
        password_path: password