vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /uploads/media
            upload_destination: "%kernel.project_dir%/public/uploads/media"
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        technical_document:
            uri_prefix: /uploads/tech_docs
            upload_destination: "%kernel.project_dir%/public/uploads/tech_docs"
            namer: Vich\UploaderBundle\Naming\OrignameNamer
