controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# used in security.yaml firewalls: login: json_login: check_path
auth:
    path: /auth
    methods: ['POST']

api_refresh_token:
    path: /token/refresh

api_token_invalidate:
    path: /token/invalidate
